'''
 *  $Id: SConstruct,  DAMPE $
 *----------------------------------------------------------
 *  This file is generated by dmpsw-expand
 *----------------------------------------------------------
'''

import os

target='DmpSvcDatabase'

print "---> compiling: %s\n" % target
#--------------------------------------------------------------------
# environment
env = Environment(ENV = os.environ)
env.ParseConfig("dmpsw-config --include --libs")
env.ParseConfig("python-config --include --libs")
env.ParseConfig("root-config --cflags --libs")
#env.ParseConfig("clhep-config --include --libs")
#env.PrependENVPath('PATH', os.environ['G4INSTALL']+'/../../../bin')    # 2 lines for G4
#env.ParseConfig("geant4-config --cflags --libs")
#env.MergeFlags('-fopenmp')

#-------------------------------------------------------------------
# include dir. and external libs
env.Prepend(CPPPATH=['./include'])
env.Append(LIBS=['boost_python','boost_system','boost_filesystem'])
#env.Append(LIBS=['YourEventModule'])   # link your event module, only for algorithm

#-------------------------------------------------------------------
# include dir. and external libs
includeDir='./include'

# installation
#--------------------------------------------------------------------
for tmp in os.listdir(includeDir):
    if "." not in tmp[0] and "LinkDef" not in tmp and "Dictionary" not in tmp and ".h" in tmp:
        Default(Command(os.environ['DMPSWWORK']+'/include/'+tmp,includeDir+'/'+tmp,Copy("$TARGET","$SOURCE")))


#-------------------------------------------------------------------
# main build
goal=env.SharedLibrary(target,Glob('./src/*.cc'))
Default(env.InstallAs(os.environ['DMPSWWORK']+'/lib/lib'+target+".dylib",goal))
Default(env.InstallAs(os.environ['DMPSWWORK']+'/lib/lib'+target+".so",goal))
